git:
  depth: 1
matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      language: python
      python:
        - "2.7"
        - "3.7"
    - os: osx
      language: generic
      addons:
        homebrew:
          packages:
            - llvm
            - boost
  allow_failures:
    - python: "3.7"
before_install:
  - pip install --upgrade pip
install:
  - pip install cython
  - pip install numpy scipy
  - pip install coveralls
  - pip install .
# command to run tests
script:
  - coverage run --source ./ -m unittest discover unittest/ -p "*" -v
after_success:
  - coveralls
