language: python
python:
  - "2.7"
install:
  - pip install cython
  - pip install numpy scipy
  - pip install coveralls
  - pip install .
# command to run tests
script:
  - coverage --source ./ run -m unittest discover unittest/ -p "*" -v
after_success:
  - coveralls