language: python
python:
  - "2.7"
before_install:
  - pip install --upgrade pip
install:
  - pip install cython
  - pip install numpy scipy
  - pip install coveralls
  - pip install .
# command to run tests
script:
  - coverage run --source ./ -m unittest discover unittest/ -p "*" -v
after_success:
  - coveralls
