language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - python -m unittest discover unittest/ -p "*" -v
